### ISSUE TITLE
[Bug?] Drag-to-Draw Functions Unusually on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by ZAdamMac** [hairymnstr/fontedit#1]
Hello. I maintain a modest fork of fontedit to support some custom exporter definitions for a long-running hobby-tech project I've been working on.

A recent change in that project requires me to redraw several fonts and I've noticed that the drag-draw feature added several years ago does not seem to function as intended. I tried updating my fork to your most recent commit from a few weeks ago and find that I still cannot drag-to-draw.

I've included a video, below, of the unexpected behavior. In short: instead of clicking and dragging toggling all "cells" the cursor passes over, it appears to treat the pixel I've clicked first as its own distinct issue and just sort of drags that around without changing any other cells.

I suspected it may be a dependency issue but I appear to have the most recent version of gi installed:
```
patches@limitless:~$ python3 -c 'import gi;print(gi.__version__)'
3.42.1
```

[Screencast from 2023-12-03 09:58:57 PM.webm](https://github.com/hairymnstr/fontedit/assets/26860397/9afbf6be-0e3f-4291-b8fa-8cc377ef1e8c)

**Comment by hairymnstr** [comment]
I am running 22.04 and have been building an IBM BIOS like font recently with no issues.  I've checked the version of gi matches yours and everything is committed and pushed.

The drag to draw feature uses the drag-and-drop methods so I'm not surprised the first pixel you change appears to get dragged around with the mouse.  I see that too. But on my machine all the pixels I drag the initial pixel over change to the same state as the dragged pixel.

Is there any console output on the command line while you try drawing?

**Comment by ZAdamMac** [comment]
Actually no, which is slightly unusual; up until a day or two ago I'd get console output quite frequently.

Is there a `--debug` flag or similar I can pass to make the line output more verbose?

**Comment by hairymnstr** [comment]
I've never had problems with it so never implemented any debug features.  Just updated my system to make sure it's not some library thing but still working as designed for me on 22.04

**Comment by ZAdamMac** [comment]
Strange. I'll try on another machine at some point over the next couple days. Perhaps it's an issue with some other package I have installed or some other sort of knock-on effect.

**Comment by ZAdamMac** [comment]
To add some color to this I haven't been able to get the functionality to work anywhere, including on a fresh install in a clean VM.

I did just get done one small test where all I changed between the current master commit on this repo was two lines in `char_widget.py` to add basic print() statements for debugging purposes on lines 81 and 85. From this I've been able to work out that click events are being registered, but that even in a drag, the `pixel_drag2` method is just never being called.

If you can confirm that the version of that file which is currently hosted on the repo is the same version you're successfully testing, I'm going got throw up my hands in defeat to Poettering and assume that something weird is happening between my pointing device and the application and that the problem is entirely on my end, somehow.
